return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "ansible-language-server",
        "azure-pipelines-language-server",
        "bash-language-server",
        "codelldb",
        -- "csharp-language-server", Not on latest version, run 'dotnet tool install --global csharp-ls' instead
        "csharpier",
        "cueimports",
        "delve",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "doctoc",
        "dot-language-server",
        "earthlyls",
        "gradle-language-server",
        "graphql-language-service-cli",
        "hadolint",
        "hclfmt",
        "helm-ls",
        "html-lsp",
        "htmx-lsp",
        "impl",
        "java-debug-adapter",
        "java-test",
        "jdtls",
        "jq",
        "json-lsp",
        "jsonnet-language-server",
        "jsonnetfmt",
        "kcl",
        "kotlin-language-server",
        "ktlint",
        "lua-language-server",
        "markdown-toc",
        "markdownlint-cli2",
        "marksman",
        "netcoredbg",
        "opa",
        "powershell-editor-services",
        "regols",
        "ruff",
        "ruff-lsp",
        "sqlfluff",
        "sqlfmt",
        "stylua", -- Used to format Lua code
        "tailwindcss-language-server",
        "templ",
        "vue-language-server",
        "yaml-language-server",
        "yamlfmt",
        "zls",
        -- "snyk-ls",
      },
    },
  },
}
